<center><h2><b>NumPy library</b></h2></center>
<h3><p>NumPy is a powerful <b>Python library</b> that makes working with large set of numbers much easier and faster. It provides a way to create and manipulate arrays, which are like lists but more efficient for numerical computations.</p></h3>

### (1) Creation of nested list object

In [1]:
mat = [[2,4,6,8],[3,5,7,9],[12,14,16,18],[11,13,15,17]]
print(type(mat))

<class 'list'>


In [ ]:
mat[2][1]

### (2) Multiplying array element

In [ ]:
mat[1][1] * 2

In [ ]:
for row in mat:
    for col in range(len(mat)):
        row[col] = row[col] * 2

In [ ]:
mat

### Array creation & slicing

In [ ]:
import numpy as py
# a = py.array([1,2,3,4,5,6])
a1 = py.array([[1,2],[4,5],[5,6],[6,7]])
# py.shape(a)
# print(a.ndim)
# a[-1]
a1[-1:-2:-1]
# a[4:2:-1] # traversed in reverse order start and stop are positive but stepping is only -ve, so 5 is 4th index, and 4 is 3rd index

### Array creation and it's operations

In [ ]:
Nums = py.array([11,22,33,44,55])
# Nums<20
# Nums>15
# Nums != 10

In [ ]:
#Generate random integer with specified numbers between given range
import numpy as py
py.random.randint(1,10,6).reshape(3,2,1) # reshape(depth/level_of_array/No_of_2Darray, row, column)

### Extracting the required array using slicing

In [ ]:
TwoD_arr = py.array([[2,4,6,8,10],[1,3,5,7,9],[1,2,3,4,5]])
print(TwoD_arr)
print("\n After slicing:")
# TwoD_arr[:3,:2].shape
# TwoD_arr[1:3,1:3]
TwoD_arr[:3,:2]

### (3) printing array in the form of matrix ($ pip3 install numpy)

In [ ]:
import numpy as np
matrix = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(type(matrix))
print(matrix)

In [ ]:
print(matrix)

In [ ]:
matrix[0][1]

In [ ]:
matrix[0,1]

### (4) Creating array with different type

In [ ]:
np.array([[1, 2, 3], ['a', 'b', 'c']])

In [ ]:
import numpy as np

arr = np.array(['hello', 'world', 'numpy'])
print(arr)
# print(arr.reshape(3,1,1))

In [ ]:
matrix = np.array([
     [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])
# print(type(matrix))
print(matrix)
# 3DArray_Indexing[2DArr_position][row][col] or 3DArray_Indexing[depth_index][row_index][column_index]
print(matrix[0,1,2])

In [ ]:
print(matrix)

In [ ]:
matrix[1][1][2]

In [ ]:
matrix[1, 1, 2]

### (5) Array Operations

In [ ]:
m1 = np.array([[11,22,11],[33,44,55]])
print(m1.shape)
# m1.ndim
# m1.size
print(m1)

In [5]:
matrix = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1,]])
2 * matrix

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [7]:
import numpy as np
second_matrix = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
second_matrix - matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
matrix = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]]) # 1*1,1*1,1*1; 2*2,2*2,2*2, 3*3,3*3,3*3
matrix * matrix

array([[1, 1, 1],
       [4, 4, 4],
       [9, 9, 9]])

In [9]:
matrix @ matrix

array([[ 6,  6,  6],
       [12, 12, 12],
       [18, 18, 18]])

In [ ]:
np.matmul(matrix, matrix)

### (6) Common array operations

In [ ]:
Num_mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Get a tuple of axis length
matrix.shape

# Get an array of the diagonal entries
matrix.diagonal()

# Get a 1-dimensional array of all entries
matrix.flatten()

# Get the transpose of an array
matrix.transpose()

# Calculate the minimum entry
matrix.min()

# Calculate the maximum entry
matrix.max()

# Calculate the average value of all entries
matrix.mean()

# Calculate the sum of all entries
matrix.sum()

## (7) Stacking and Shaping Arrays: Two arrays can be stacked <b>vertically</b> using np.vstack() or <b>horizontally</b> using np.hstack() if their axis sizes match:

In [14]:
import numpy as np
Mat_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Mat_B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

#print array in vertically
# np.hstack((Mat_A, Mat_B))
np.vstack((Mat_A, Mat_B))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [11]:
#print array in horizontally
np.hstack((Mat_A, Mat_B))
# np.hstack([Mat_B])

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
Mat_A.reshape(9,1)

### (8) arange() function in Numpy

In [15]:
import numpy
Seq_mat = numpy.arange(1,13,3)
# print(Seq_mat)
Seq_mat

array([ 1,  4,  7, 10])

### (9) arange() with stepping value

In [16]:
np.arange(1, 13).reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### (10) create an array with random numbers

In [15]:
numpy.random.random([2,2])

NameError: name 'numpy' is not defined

###### <center><h1>Simple Problems<h1></center>

## (1) Create a 3 × 3 array named first_matrix that includes the numbers 3 through 11 by using arange() function and  reshape the array object

In [ ]:
import numpy as np

# Create a NumPy array with numbers from 3 to 11
numbers = np.arange(3, 12)

# Reshape the array into a 3x3 matrix
first_matrix = numbers.reshape(3, 3)

print(first_matrix)

### (2) Find array mean.

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([11,22,33,44,55])
# arr = np.random.random([2,3])

# Calculate the mean of the array
mean_value = np.mean(arr)

print("Array:", arr)
print("Mean:", mean_value)

### (3) Display the minimum, maximum and mean of all entries in first_matrix.

In [ ]:
# Display the min, max and mean of all entries in the matrix
print(f"Min is {first_matrix.min()}")
print(f"Max is {first_matrix.max()}")
print(f"Mean is {first_matrix.mean()}")

### (4) Square every entry in first_matrix using the ** operator, and save the results in an array named second_matrix.

In [ ]:
# Square every entry and save in a new matrix
second_matrix = first_matrix**2

### (5) Stack first_matrix on top of second_matrix and save the results in an array named third_matrix. Also Test by placing them side-by-side

In [ ]:
# Put first_matrix on top of second_matrix
third_matrix = np.vstack([first_matrix, second_matrix])

In [ ]:
third_matrix

### (6) Use the @ operator to calculate the matrix product of third_matrix by first_matrix.

In [ ]:
# Calculate the dot product of third_matrix by first_matrix
print(third_matrix @ first_matrix)

### (7) Reshape third_matrix into an array of dimensions 3 × 3 × 2.

In [ ]:
# Reshape third_matrix into a 3x3x2 matrix: reshape(dimension x row x column)
third_matrix = third_matrix.reshape(3, 3, 2)
print(third_matrix)

In [ ]:
third_matrix.ndim