In [1]:
import numpy as np
x = np.array([
    23,
    35,
    2,
    28,
    9,
    32,
    25,
    10,
])


In [2]:
y = np.array([
    486,
    747,
    81,
    581,
    112,
    728,
    445,
    128
])

In [7]:
xAvg = sum(x)/len(x)
yAvg = sum(y)/len(y)

In [45]:
xdev = x - xAvg #array
ydev = y - yAvg

In [46]:
xdev2 = xdev**2 #array
ydev2 = ydev**2

In [47]:
x_xIntoy_yAvg = (x-xAvg)*(y-yAvg) #array

x_xAvgIntoy_yAvg

array([ 181.25, 4835.75, 6151.25, 1256.25, 3467.25, 3616.75,  141.75,
       2997.75])

In [33]:
x_xAvgIntoy_yAvg_AVG = sum(x_xAvgIntoy_yAvg)/len(x_xAvgIntoy_yAvg)
x_xAvgIntoy_yAvg_AVG

2831.0

In [34]:
xdev2

array([  6.25, 210.25, 342.25,  56.25, 132.25, 132.25,  20.25, 110.25])

In [37]:
m = x_xAvgIntoy_yAvg_AVG / (sum(xdev2)/len(xdev2))
m

22.423762376237622

In [38]:
# yp = m*x+c

c = yAvg - m*xAvg
c

-46.18712871287124

In [41]:
yp = m*x + c
yp

array([469.55940594, 738.64455446,  -1.33960396, 581.67821782,
       155.62673267, 671.37326733, 514.40693069, 178.05049505])

In [43]:
yp_y = yp-y
yp_y

array([-16.44059406,  -8.35544554, -82.33960396,   0.67821782,
        43.62673267, -56.62673267,  69.40693069,  50.05049505])

In [49]:
yp_y2 = yp_y**2 #array
yp_y2

array([2.70293133e+02, 6.98134702e+01, 6.77981038e+03, 4.59979414e-01,
       1.90329180e+03, 3.20658685e+03, 4.81732203e+03, 2.50505205e+03])

In [51]:
R2 = 1 - sum(yp_y2)/len(yp_y2) / sum(ydev**2)/len(ydev)
R2

0.9994207312030791